### ISSUE TITLE
Client not emitting events

### ISSUE THREAD

**Issue by sidd** [dcposch/webtorrent-remote#2]
Thanks for writing this utility 😄 

I'm not able to get the example working since `torrent` never fires events on the client besides `error` and `warning`. I can PR my current fork if it's not something you're already working on.

**Comment by dcposch** [comment]
Fixed. If you're on the latest version (`v0.0.9`), torrents should fire all of the usual events:

* `infohash`
* `metadata`
* `download`
* `upload`
* `done`

...as well as a new event that isn't in `webtorrent.js`. It fires regularly, whenever the client gets an update from the server on torrent progress, # of peers connected, etc:
* `update`

**Comment by dcposch** [comment]
LMK if that works!
