### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by feross** [dcposch/webtorrent-remote#4]
Hey @dcposch,

What do you think about releasing this as 1.0.0?

These days, it's common to start all but the most experimental packages off at 1.0.0 instead of 0.0.0.

The semver operators `^` and `~` behave weirdly below 1.0.0, making it hard for dependents like Brave to automatically inherit minor and patch versions without constantly bumping their `package.json`.

What do you say?

**Comment by dcposch** [comment]
Sure. Didn't you have a fix you wanted to do first?

**Comment by feross** [comment]
The fix was in webtorrent itself :) Merging and releasing https://github.com/dcposch/webtorrent-remote/pull/3 did the trick!

**Comment by dcposch** [comment]
Done

**Comment by feross** [comment]
🎉
