### ISSUE TITLE
use webtorrent hostname option to mitigate DNS rebinding

### ISSUE THREAD

**Issue by diracdeltas** [dcposch/webtorrent-remote#9]
see https://github.com/webtorrent/webtorrent/pull/1260

**Comment by diracdeltas** [comment]
@feross @dcposch either of you able to take this? thanks

**Comment by feross** [comment]
See comment: https://github.com/brave/browser-laptop/issues/12616#issuecomment-380627354

**Comment by diracdeltas** [comment]
thanks!
